apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- if .Values.aws.irsaRoleArn }}
    eks.amazonaws.com/role-arn: {{ .Values.aws.irsaRoleArn | quote }}
    {{- end }}
  labels:
    app.kubernetes.io/name: bamboo-controller
