// SPDX-License-Identifier: AGPL-3.0-or-later

package repo

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/hanfour/bamboo/apps/controller/internal/db"
)

// UserInvitations is the repository for user_invitations.
//
// Phase A surface: Create + ListByTenant. Redeem / Revoke live in
// follow-ups once the OIDC-callback "accept on first login" wiring
// is designed and email delivery is decided.
type UserInvitations struct {
	pool *db.Pool
}

// NewUserInvitations constructs a UserInvitations repository.
func NewUserInvitations(pool *db.Pool) *UserInvitations {
	return &UserInvitations{pool: pool}
}

// UserInvitation is the domain model. The plaintext token is never
// stored — TokenHash is the bcrypt hash of what was minted at create
// time. The Status is derived in the renderer:
//
//	revoked_at  set                       → revoked
//	accepted_at set                       → accepted
//	expires_at  past && unredeemed        → expired
//	else                                  → pending
type UserInvitation struct {
	ID         uuid.UUID
	TenantID   uuid.UUID
	Email      string
	IsAdmin    bool
	TokenHash  string
	InvitedBy  *uuid.UUID
	CreatedAt  time.Time
	ExpiresAt  time.Time
	AcceptedAt *time.Time
	AcceptedBy *uuid.UUID
	RevokedAt  *time.Time
	RevokedBy  *uuid.UUID
}

// Create inserts a new invitation. The caller is responsible for
// hashing the token before calling — same pattern as PreAuthKeys.
// The partial unique index in the schema (one pending invite per
// (tenant, lower(email))) will fail the insert with a duplicate-key
// error when an active invitation already exists; the caller should
// surface that as a 409.
func (r *UserInvitations) Create(ctx context.Context, inv *UserInvitation) (*UserInvitation, error) {
	// ID is generated by the caller and embedded in the token so the
	// redeem path can O(1) lookup the row by parsing the prefix
	// (mirrors the PreAuthKey pattern). We pass it explicitly to
	// INSERT rather than relying on the gen_random_uuid() default.
	var out UserInvitation
	err := r.pool.QueryRow(ctx, `
		INSERT INTO user_invitations (
		    id, tenant_id, email, is_admin, token_hash, invited_by, expires_at
		) VALUES ($1, $2, $3, $4, $5, $6, $7)
		RETURNING id, tenant_id, email, is_admin, token_hash, invited_by,
		          created_at, expires_at, accepted_at, accepted_by, revoked_at, revoked_by
	`, inv.ID, inv.TenantID, inv.Email, inv.IsAdmin, inv.TokenHash, inv.InvitedBy, inv.ExpiresAt).Scan(
		&out.ID, &out.TenantID, &out.Email, &out.IsAdmin, &out.TokenHash, &out.InvitedBy,
		&out.CreatedAt, &out.ExpiresAt, &out.AcceptedAt, &out.AcceptedBy, &out.RevokedAt, &out.RevokedBy,
	)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListByTenant returns every invitation in the tenant ordered by
// creation time (newest first). Accepted + revoked rows are included
// so the admin Users page can show history; the renderer derives
// status per row.
func (r *UserInvitations) ListByTenant(ctx context.Context, tenantID uuid.UUID) ([]*UserInvitation, error) {
	rows, err := r.pool.Query(ctx, `
		SELECT id, tenant_id, email, is_admin, token_hash, invited_by,
		       created_at, expires_at, accepted_at, accepted_by, revoked_at, revoked_by
		FROM user_invitations
		WHERE tenant_id = $1
		ORDER BY created_at DESC
	`, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var out []*UserInvitation
	for rows.Next() {
		var inv UserInvitation
		if err := rows.Scan(
			&inv.ID, &inv.TenantID, &inv.Email, &inv.IsAdmin, &inv.TokenHash, &inv.InvitedBy,
			&inv.CreatedAt, &inv.ExpiresAt, &inv.AcceptedAt, &inv.AcceptedBy, &inv.RevokedAt, &inv.RevokedBy,
		); err != nil {
			return nil, err
		}
		out = append(out, &inv)
	}
	return out, rows.Err()
}
