// SPDX-License-Identifier: AGPL-3.0-or-later

package repo

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/hanfour/bamboo/apps/controller/internal/db"
)

// UserInvitations is the repository for user_invitations.
//
// Phase A surface: Create + ListByTenant. Redeem / Revoke live in
// follow-ups once the OIDC-callback "accept on first login" wiring
// is designed and email delivery is decided.
type UserInvitations struct {
	pool *db.Pool
}

// NewUserInvitations constructs a UserInvitations repository.
func NewUserInvitations(pool *db.Pool) *UserInvitations {
	return &UserInvitations{pool: pool}
}

// UserInvitation is the domain model. The plaintext token is never
// stored — TokenHash is the bcrypt hash of what was minted at create
// time. The Status is derived in the renderer:
//
//	revoked_at  set                       → revoked
//	accepted_at set                       → accepted
//	expires_at  past && unredeemed        → expired
//	else                                  → pending
type UserInvitation struct {
	ID         uuid.UUID
	TenantID   uuid.UUID
	Email      string
	IsAdmin    bool
	TokenHash  string
	InvitedBy  *uuid.UUID
	CreatedAt  time.Time
	ExpiresAt  time.Time
	AcceptedAt *time.Time
	AcceptedBy *uuid.UUID
	RevokedAt  *time.Time
	RevokedBy  *uuid.UUID
}

// Create inserts a new invitation. The caller is responsible for
// hashing the token before calling — same pattern as PreAuthKeys.
// The partial unique index in the schema (one pending invite per
// (tenant, lower(email))) will fail the insert with a duplicate-key
// error when an active invitation already exists; the caller should
// surface that as a 409.
func (r *UserInvitations) Create(ctx context.Context, inv *UserInvitation) (*UserInvitation, error) {
	// ID is generated by the caller and embedded in the token so the
	// redeem path can O(1) lookup the row by parsing the prefix
	// (mirrors the PreAuthKey pattern). We pass it explicitly to
	// INSERT rather than relying on the gen_random_uuid() default.
	var out UserInvitation
	err := r.pool.QueryRow(ctx, `
		INSERT INTO user_invitations (
		    id, tenant_id, email, is_admin, token_hash, invited_by, expires_at
		) VALUES ($1, $2, $3, $4, $5, $6, $7)
		RETURNING id, tenant_id, email, is_admin, token_hash, invited_by,
		          created_at, expires_at, accepted_at, accepted_by, revoked_at, revoked_by
	`, inv.ID, inv.TenantID, inv.Email, inv.IsAdmin, inv.TokenHash, inv.InvitedBy, inv.ExpiresAt).Scan(
		&out.ID, &out.TenantID, &out.Email, &out.IsAdmin, &out.TokenHash, &out.InvitedBy,
		&out.CreatedAt, &out.ExpiresAt, &out.AcceptedAt, &out.AcceptedBy, &out.RevokedAt, &out.RevokedBy,
	)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetByID returns the invitation row by primary key. ErrNotFound for
// unknown / soft-deleted ids; the redeem path uses this to look up
// the row referenced by the embedded id in the invite token.
func (r *UserInvitations) GetByID(ctx context.Context, id uuid.UUID) (*UserInvitation, error) {
	var inv UserInvitation
	err := r.pool.QueryRow(ctx, `
		SELECT id, tenant_id, email, is_admin, token_hash, invited_by,
		       created_at, expires_at, accepted_at, accepted_by, revoked_at, revoked_by
		FROM user_invitations
		WHERE id = $1
	`, id).Scan(
		&inv.ID, &inv.TenantID, &inv.Email, &inv.IsAdmin, &inv.TokenHash, &inv.InvitedBy,
		&inv.CreatedAt, &inv.ExpiresAt, &inv.AcceptedAt, &inv.AcceptedBy, &inv.RevokedAt, &inv.RevokedBy,
	)
	if err != nil {
		return nil, asNotFound(err)
	}
	return &inv, nil
}

// MarkAccepted atomically flips the invitation to accepted by the
// given user. Guarded against double-redeem via the WHERE clause —
// returns ErrNotFound when the row was already accepted / revoked /
// when no row matches, so concurrent OIDC callbacks racing for the
// same invitation can't both create sessions.
func (r *UserInvitations) MarkAccepted(ctx context.Context, id, userID uuid.UUID) error {
	tag, err := r.pool.Exec(ctx, `
		UPDATE user_invitations
		   SET accepted_at = now(),
		       accepted_by = $2
		 WHERE id = $1
		   AND accepted_at IS NULL
		   AND revoked_at IS NULL
	`, id, userID)
	if err != nil {
		return err
	}
	if tag.RowsAffected() == 0 {
		return ErrNotFound
	}
	return nil
}

// MarkRevoked atomically flips a pending invitation to revoked. The
// WHERE guards against revoking an already-accepted row (a redeemed
// invite is history — revoking it wouldn't unmake the user) or
// double-revoking. ErrNotFound when there's no eligible row, so the
// handler can return 404 / 409 to distinguish "already revoked" from
// "never existed". Accepted by the WHERE clause means the row stays
// terminal in its current state and the caller can move on.
func (r *UserInvitations) MarkRevoked(ctx context.Context, id, userID uuid.UUID) error {
	tag, err := r.pool.Exec(ctx, `
		UPDATE user_invitations
		   SET revoked_at = now(),
		       revoked_by = $2
		 WHERE id = $1
		   AND accepted_at IS NULL
		   AND revoked_at IS NULL
	`, id, userID)
	if err != nil {
		return err
	}
	if tag.RowsAffected() == 0 {
		return ErrNotFound
	}
	return nil
}

// ListByTenant returns every invitation in the tenant ordered by
// creation time (newest first). Accepted + revoked rows are included
// so the admin Users page can show history; the renderer derives
// status per row.
func (r *UserInvitations) ListByTenant(ctx context.Context, tenantID uuid.UUID) ([]*UserInvitation, error) {
	rows, err := r.pool.Query(ctx, `
		SELECT id, tenant_id, email, is_admin, token_hash, invited_by,
		       created_at, expires_at, accepted_at, accepted_by, revoked_at, revoked_by
		FROM user_invitations
		WHERE tenant_id = $1
		ORDER BY created_at DESC
	`, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var out []*UserInvitation
	for rows.Next() {
		var inv UserInvitation
		if err := rows.Scan(
			&inv.ID, &inv.TenantID, &inv.Email, &inv.IsAdmin, &inv.TokenHash, &inv.InvitedBy,
			&inv.CreatedAt, &inv.ExpiresAt, &inv.AcceptedAt, &inv.AcceptedBy, &inv.RevokedAt, &inv.RevokedBy,
		); err != nil {
			return nil, err
		}
		out = append(out, &inv)
	}
	return out, rows.Err()
}
