-- +goose Up
-- +goose StatementBegin

-- Webhook subscriptions (§4 P2 commercial / SaaS integration).
--
-- A subscription is an outbound HTTP endpoint that the controller
-- POSTs to whenever an audited event happens in the subscribed
-- tenant. The event payload is signed with HMAC-SHA256 over the
-- request body using the subscription's `secret`, surfaced in the
-- `X-Bamboo-Signature: sha256=<hex>` header so the receiver can
-- verify integrity + origin.
--
-- Field rationale:
--   url          target endpoint. POST body is JSON.
--   secret       HMAC key. Generated by the controller on create,
--                shown to the admin once in the response, hashed-
--                at-rest is NOT used here — webhook secrets are
--                symmetric (the receiver needs the same plaintext
--                to verify the sig). The tenant boundary + the
--                admin-only REST surface are the security envelope.
--   event_types  optional allowlist. Empty array = subscribe to
--                every audited event in the tenant. Filled = only
--                deliver events whose Action prefix matches one of
--                the strings (e.g. "peer.register", "policy.update").
--                Prefix match rather than exact match leaves room
--                for sub-actions like "peer.routes.approve" to
--                inherit the "peer." subscriber.
--   description  free-text label for the admin UI list.
--   active       soft-disable switch. An inactive subscription
--                stops receiving deliveries but the row stays so
--                the admin can re-enable without re-minting the
--                secret.
--
-- No delivery-attempt log table in v1 — keeps the migration small
-- + lets us iterate on the column shape after we see real failure
-- modes. The Publisher logs delivery failures via slog.
CREATE TABLE webhook_subscriptions (
    id           UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id    UUID        NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    url          TEXT        NOT NULL,
    secret       TEXT        NOT NULL,
    event_types  TEXT[]      NOT NULL DEFAULT '{}',
    description  TEXT,
    active       BOOLEAN     NOT NULL DEFAULT true,
    created_by   UUID                 REFERENCES users(id) ON DELETE SET NULL,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Publisher hot path: "give me active subscriptions for tenant X".
-- The index covers that exactly. We don't index on event_types
-- because the array is small (typically 0-5 entries) and Postgres
-- scans the array faster than a GIN index when the table is small.
CREATE INDEX webhook_subscriptions_tenant_active_idx
    ON webhook_subscriptions (tenant_id, active);

-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE IF EXISTS webhook_subscriptions;
-- +goose StatementEnd
